// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"backend/app/question/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: GetUserHandler(serverCtx),
			},
		},
	)
}
