// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"backend/app/university/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/university/addcollege",
				Handler: AddCollegeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/university/addyear",
				Handler: AddYearHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/university/addmajor",
				Handler: AddMajorHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/university/addclass",
				Handler: AddClassHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/university/addstudent",
				Handler: AddStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/university/getstudentinfo",
				Handler: GetStudentInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/university/getcollegelist",
				Handler: GetCollegeListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/university/getyearlist",
				Handler: GetYearListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/university/getmajorlist",
				Handler: GetMajorListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/university/getclasslist",
				Handler: GetClassListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/university/getstudentlist",
				Handler: GetStudentListHandler(serverCtx),
			},
		},
	)
}
