// Code generated by goctl. DO NOT EDIT!
// Source: login.proto

package server

import (
	"context"

	"user/rpc/login/internal/logic"
	"user/rpc/login/internal/svc"
	"user/rpc/login/login"
)

type LoginerServer struct {
	svcCtx *svc.ServiceContext
	login.UnimplementedLoginerServer
}

func NewLoginerServer(svcCtx *svc.ServiceContext) *LoginerServer {
	return &LoginerServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginerServer) Login(ctx context.Context, in *login.LoginReq) (*login.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
