// Code generated by goctl. DO NOT EDIT!
// Source: login.proto

package server

import (
	"context"

	"user/rpc/login/internal/logic"
	"user/rpc/login/internal/svc"
	"user/rpc/login/login"
)

type LoginServer struct {
	svcCtx *svc.ServiceContext
	login.UnimplementedLoginServer
}

func NewLoginServer(svcCtx *svc.ServiceContext) *LoginServer {
	return &LoginServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginServer) Login(ctx context.Context, in *login.LoginReq) (*login.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
