// Code generated by goctl. DO NOT EDIT.
package types

type QuestionReq struct {
	QuestionId int `json:"question_id"`
}

type QuestionResp struct {
	QuestionDesc interface{} `json:"question_desc"`
	OptionA      interface{} `json:"option_a"`
	OptionB      interface{} `json:"option_b"`
}
