// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Username         string `json:"username"`
	Nickname         string `json:"nickname"`
	Gender           string `json:"gender"`
	BindingStudentId string `json:"binding_student_id"`
}

type JwtToken struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type RegisterReq struct {
	Username string `json:"username"`
	NickName string `json:"nickname"`
	Password string `json:"password"`
	Gender   string `json:"gender"`
}

type RegisterResp struct {
	Msg string `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Msg string   `json:"msg"`
	Jwt JwtToken `json:"jwt_token"`
}

type GetUserInfoReq struct {
	Username string `json:"username"`
}

type GetUserInfoResp struct {
	UserInfoResp UserInfo `json:"userinfo"`
}
