// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `json:"username"`
	NickName string `json:"nickname"`
	Password string `json:"password"`
	Gender   string `json:"gender"`
}

type RegisterResp struct {
	Msg string `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Gender   string `json:"gender"`
}
