// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"backend/app/question/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/question/create",
				Handler: CreateQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/question/delete",
				Handler: DeleteQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/question/get",
				Handler: GetQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/question/getidlist",
				Handler: GetQuestionIdListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/question/getlist",
				Handler: GetQuestionListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/question/edit",
				Handler: EditQuestionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
