// Code generated by goctl. DO NOT EDIT.
package types

type AddCollegeReq struct {
	CollegeId   int64  `json:"college_id"`
	CollegeName string `json:"college_name"`
}

type AddCollegeResp struct {
	Msg string `json:"msg"`
}
