// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"backend/app/data/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/data/add",
				Handler: AddTestDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/data/getlist",
				Handler: GetTestDataListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/data/get",
				Handler: GetLatestDataHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
