// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Age      int    `json:"age"`
	Gender   string `json:"gender"`
}

type RegisterResp struct {
	Msg string `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Username     string `json:"username"`
	Age          int64  `json:"age"`
	Gender       string `json:"gender"`
	Token        string `json:"token"`
	ExpireTime   int64  `json:"expire_time"`
	RefreshAfter int64  `json:"refreshAfter"`
}
