// Code generated by goctl. DO NOT EDIT.
package types

type AddTestDataReq struct {
	Username  string `json:"username"`
	Type      string `json:"type"`
	StudentId string `json:"student_id"`
	Selection string `json:"selection"`
}

type AddTestDataResp struct {
	Msg string `json:"msg"`
}

type Data struct {
	Username  string `json:"username"`
	StudentId string `json:"student_id"`
	Type      string `json:"type"`
	Time      string `json:"time"`
	Selection string `json:"selection"`
}

type GetTestDataListReq struct {
}

type GetTestDataListResp struct {
	List []Data `json:"data_list"`
}

type GetTestDataReq struct {
	DataId int64 `json:"data_id"`
}

type GetTestDataResp struct {
	DataInfo Data `json:"data_info"`
}

type GetLatestDataReq struct {
}

type GetLatestDataResp struct {
	Type string `json:"type"`
}

type GetDataIdListReq struct {
}

type GetDataIdListResp struct {
	DataIdList []int64 `json:"data_id_list"`
}
