// Code generated by goctl. DO NOT EDIT.
package types

type Question struct {
	QuestionId   int64  `json:"question_id"`
	QuestionDesc string `json:"question_desc"`
	OptionA      string `json:"option_a_desc"`
	TargetA      string `json:"option_a_target"`
	OptionB      string `json:"option_b_desc"`
	TargetB      string `json:"option_b_target"`
}

type GetQuestionReq struct {
	QuestionId int `form:"id"`
}

type GetQuestionResp struct {
	QuestionInfo Question `json:"question_info"`
}

type GetQuestionIdListReq struct {
}

type GetQuestionIdListResp struct {
	QuestionIdList []int64 `json:"question_id_list"`
}

type CreateQuestionReq struct {
	QuestionDesc  string `json:"question_desc"`
	OptionADesc   string `json:"option_a_desc"`
	OptionATarget string `json:"option_a_target"`
	OptionBDesc   string `json:"option_b_desc"`
	OptionBTarget string `json:"option_b_target"`
}

type CreateQuestionResp struct {
	Msg string `json:"msg"`
}

type DeleteQuestionReq struct {
	QuestionId int64 `form:"id"`
}

type DeleteQuestionResp struct {
	Msg string `json:"msg"`
}

type EditQuestionReq struct {
	QuestionId   int64  `json:"question_id"`
	QuestionDesc string `json:"question_desc"`
	OptionA      string `json:"option_a_desc"`
	TargetA      string `json:"option_a_target"`
	OptionB      string `json:"option_b_desc"`
	TargetB      string `json:"option_b_target"`
}

type EditQuestionResp struct {
	Msg string `json:"msg"`
}
