// Code generated by goctl. DO NOT EDIT!

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInfoFieldNames          = builder.RawFieldNames(&UserInfo{}, true)
	userInfoRows                = strings.Join(userInfoFieldNames, ",")
	userInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(userInfoFieldNames, "create_time", "update_time"), ",")
	userInfoRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userInfoFieldNames, "username", "create_time", "update_time"))

	cachePublicUserInfoUsernamePrefix = "cache:public:userInfo:username:"
	cachePublicUserInfoNicknamePrefix = "cache:public:userInfo:nickname:"
)

type (
	userInfoModel interface {
		Insert(ctx context.Context, data *UserInfo) (sql.Result, error)
		FindOne(ctx context.Context, username string) (*UserInfo, error)
		FindOneByNickname(ctx context.Context, nickname string) (*UserInfo, error)
		Update(ctx context.Context, data *UserInfo) error
		Delete(ctx context.Context, username string) error
	}

	defaultUserInfoModel struct {
		sqlc.CachedConn
		table string
	}

	UserInfo struct {
		Username  string    `db:"username"` // 用户名
		Nickname  string    `db:"nickname"` // 昵称
		Password  string    `db:"password"` // 密码
		Gender    string    `db:"gender"`   // 性别
		CreatedAt time.Time `db:"created_at"`
		AuthGroup string    `db:"auth_group"` // 认证权限
	}
)

func newUserInfoModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserInfoModel {
	return &defaultUserInfoModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."user_info"`,
	}
}

func (m *defaultUserInfoModel) Insert(ctx context.Context, data *UserInfo) (sql.Result, error) {
	publicUserInfoNicknameKey := fmt.Sprintf("%s%v", cachePublicUserInfoNicknamePrefix, data.Nickname)
	publicUserInfoUsernameKey := fmt.Sprintf("%s%v", cachePublicUserInfoUsernamePrefix, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, userInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Username, data.Nickname, data.Password, data.Gender, data.CreatedAt, data.AuthGroup)
	}, publicUserInfoNicknameKey, publicUserInfoUsernameKey)
	return ret, err
}

func (m *defaultUserInfoModel) FindOne(ctx context.Context, username string) (*UserInfo, error) {
	publicUserInfoUsernameKey := fmt.Sprintf("%s%v", cachePublicUserInfoUsernamePrefix, username)
	var resp UserInfo
	err := m.QueryRowCtx(ctx, &resp, publicUserInfoUsernameKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where username = $1 limit 1", userInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, username)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInfoModel) FindOneByNickname(ctx context.Context, nickname string) (*UserInfo, error) {
	publicUserInfoNicknameKey := fmt.Sprintf("%s%v", cachePublicUserInfoNicknamePrefix, nickname)
	var resp UserInfo
	err := m.QueryRowIndexCtx(ctx, &resp, publicUserInfoNicknameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where nickname = $1 limit 1", userInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, nickname); err != nil {
			return nil, err
		}
		return resp.Username, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInfoModel) Update(ctx context.Context, data *UserInfo) error {
	publicUserInfoNicknameKey := fmt.Sprintf("%s%v", cachePublicUserInfoNicknamePrefix, data.Nickname)
	publicUserInfoUsernameKey := fmt.Sprintf("%s%v", cachePublicUserInfoUsernamePrefix, data.Username)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where username = $1", m.table, userInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Username, data.Nickname, data.Password, data.Gender, data.CreatedAt, data.AuthGroup)
	}, publicUserInfoNicknameKey, publicUserInfoUsernameKey)
	return err
}

func (m *defaultUserInfoModel) Delete(ctx context.Context, username string) error {
	data, err := m.FindOne(ctx, username)
	if err != nil {
		return err
	}

	publicUserInfoNicknameKey := fmt.Sprintf("%s%v", cachePublicUserInfoNicknamePrefix, data.Nickname)
	publicUserInfoUsernameKey := fmt.Sprintf("%s%v", cachePublicUserInfoUsernamePrefix, username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where username = $1", m.table)
		return conn.ExecCtx(ctx, query, username)
	}, publicUserInfoNicknameKey, publicUserInfoUsernameKey)
	return err
}

func (m *defaultUserInfoModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicUserInfoUsernamePrefix, primary)
}

func (m *defaultUserInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where username = $1 limit 1", userInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserInfoModel) tableName() string {
	return m.table
}
