// Code generated by goctl. DO NOT EDIT.
package types

type AddCollegeReq struct {
	CollegeName string `json:"college_name"`
}

type AddCollegeResp struct {
	Msg string `json:"msg"`
}

type AddYearReq struct {
	YearName  string `json:"year_name"`
	CollegeId int    `json:"college_id"`
}

type AddYearResp struct {
	Msg string `json:"msg"`
}

type AddMajorReq struct {
	MajorName string `json:"major_name"`
	CollegeId int    `json:"college_id"`
	YearId    int    `json:"year_id"`
}

type AddMajorResp struct {
	Msg string `json:"msg"`
}

type AddClassReq struct {
	ClassName string `json:"class_name"`
	CollegeId int    `json:"college_id"`
	YearId    int    `json:"year_id"`
	MajorId   int    `json:"major_id"`
}

type AddClassResp struct {
	Msg string `json:"msg"`
}

type AddStudentReq struct {
	StudentName     string `json:"student_name"`
	CollegeId       int    `json:"college_id"`
	YearId          int    `json:"year_id"`
	MajorId         int    `json:"major_id"`
	ClassId         int    `json:"class_id"`
	IsBinding       bool   `json:"is_binding"`
	BindingUsername string `json:"binding_username"`
}

type AddStudentResp struct {
	Msg string `json:"msg"`
}
