// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: university.proto

package university

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type College struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollegeId   int64  `protobuf:"varint,1,opt,name=college_id,json=collegeId,proto3" json:"college_id,omitempty"`
	CollegeName string `protobuf:"bytes,2,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
}

func (x *College) Reset() {
	*x = College{}
	if protoimpl.UnsafeEnabled {
		mi := &file_university_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *College) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*College) ProtoMessage() {}

func (x *College) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use College.ProtoReflect.Descriptor instead.
func (*College) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{0}
}

func (x *College) GetCollegeId() int64 {
	if x != nil {
		return x.CollegeId
	}
	return 0
}

func (x *College) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

type CollegeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollegeListReq) Reset() {
	*x = CollegeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_university_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollegeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollegeListReq) ProtoMessage() {}

func (x *CollegeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollegeListReq.ProtoReflect.Descriptor instead.
func (*CollegeListReq) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{1}
}

type CollegeListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollegeList []*College `protobuf:"bytes,1,rep,name=college_list,json=collegeList,proto3" json:"college_list,omitempty"`
}

func (x *CollegeListResp) Reset() {
	*x = CollegeListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_university_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollegeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollegeListResp) ProtoMessage() {}

func (x *CollegeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollegeListResp.ProtoReflect.Descriptor instead.
func (*CollegeListResp) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{2}
}

func (x *CollegeListResp) GetCollegeList() []*College {
	if x != nil {
		return x.CollegeList
	}
	return nil
}

var File_university_proto protoreflect.FileDescriptor

var file_university_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x22, 0x4b,
	0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x49, 0x0a,
	0x0f, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x36, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x57, 0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x52, 0x70, 0x63, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x79, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_university_proto_rawDescOnce sync.Once
	file_university_proto_rawDescData = file_university_proto_rawDesc
)

func file_university_proto_rawDescGZIP() []byte {
	file_university_proto_rawDescOnce.Do(func() {
		file_university_proto_rawDescData = protoimpl.X.CompressGZIP(file_university_proto_rawDescData)
	})
	return file_university_proto_rawDescData
}

var file_university_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_university_proto_goTypes = []interface{}{
	(*College)(nil),         // 0: university.College
	(*CollegeListReq)(nil),  // 1: university.CollegeListReq
	(*CollegeListResp)(nil), // 2: university.CollegeListResp
}
var file_university_proto_depIdxs = []int32{
	0, // 0: university.CollegeListResp.college_list:type_name -> university.College
	1, // 1: university.UniversityRpc.CollegeList:input_type -> university.CollegeListReq
	2, // 2: university.UniversityRpc.CollegeList:output_type -> university.CollegeListResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_university_proto_init() }
func file_university_proto_init() {
	if File_university_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_university_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*College); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_university_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollegeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_university_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollegeListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_university_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_university_proto_goTypes,
		DependencyIndexes: file_university_proto_depIdxs,
		MessageInfos:      file_university_proto_msgTypes,
	}.Build()
	File_university_proto = out.File
	file_university_proto_rawDesc = nil
	file_university_proto_goTypes = nil
	file_university_proto_depIdxs = nil
}
