// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	classInfoFieldNames          = builder.RawFieldNames(&ClassInfo{}, true)
	classInfoRows                = strings.Join(classInfoFieldNames, ",")
	classInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(classInfoFieldNames, "create_time", "update_time"), ",")
	classInfoRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(classInfoFieldNames, "class_id", "create_time", "update_time"))

	cachePublicClassInfoClassIdPrefix = "cache:public:classInfo:classId:"
)

type (
	classInfoModel interface {
		Insert(ctx context.Context, data *ClassInfo) (sql.Result, error)
		FindOne(ctx context.Context, classId int64) (*ClassInfo, error)
		Update(ctx context.Context, data *ClassInfo) error
		Delete(ctx context.Context, classId int64) error
	}

	defaultClassInfoModel struct {
		sqlc.CachedConn
		table string
	}

	ClassInfo struct {
		ClassId   int64          `db:"class_id"`   // 班级编号
		ClassName sql.NullString `db:"class_name"` // 班级名称
		MajorId   int64          `db:"major_id"`   // 所属专业
	}
)

func newClassInfoModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultClassInfoModel {
	return &defaultClassInfoModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."class_info"`,
	}
}

func (m *defaultClassInfoModel) Insert(ctx context.Context, data *ClassInfo) (sql.Result, error) {
	publicClassInfoClassIdKey := fmt.Sprintf("%s%v", cachePublicClassInfoClassIdPrefix, data.ClassId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, classInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClassId, data.ClassName, data.MajorId)
	}, publicClassInfoClassIdKey)
	return ret, err
}

func (m *defaultClassInfoModel) FindOne(ctx context.Context, classId int64) (*ClassInfo, error) {
	publicClassInfoClassIdKey := fmt.Sprintf("%s%v", cachePublicClassInfoClassIdPrefix, classId)
	var resp ClassInfo
	err := m.QueryRowCtx(ctx, &resp, publicClassInfoClassIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where class_id = $1 limit 1", classInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, classId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClassInfoModel) Update(ctx context.Context, data *ClassInfo) error {
	publicClassInfoClassIdKey := fmt.Sprintf("%s%v", cachePublicClassInfoClassIdPrefix, data.ClassId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where class_id = $1", m.table, classInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ClassId, data.ClassName, data.MajorId)
	}, publicClassInfoClassIdKey)
	return err
}

func (m *defaultClassInfoModel) Delete(ctx context.Context, classId int64) error {
	publicClassInfoClassIdKey := fmt.Sprintf("%s%v", cachePublicClassInfoClassIdPrefix, classId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where class_id = $1", m.table)
		return conn.ExecCtx(ctx, query, classId)
	}, publicClassInfoClassIdKey)
	return err
}

func (m *defaultClassInfoModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicClassInfoClassIdPrefix, primary)
}

func (m *defaultClassInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where class_id = $1 limit 1", classInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultClassInfoModel) tableName() string {
	return m.table
}
