// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collegeInfoFieldNames          = builder.RawFieldNames(&CollegeInfo{}, true)
	collegeInfoRows                = strings.Join(collegeInfoFieldNames, ",")
	collegeInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(collegeInfoFieldNames, "create_time", "update_time"), ",")
	collegeInfoRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(collegeInfoFieldNames, "college_id", "create_time", "update_time"))

	cachePublicCollegeInfoCollegeIdPrefix = "cache:public:collegeInfo:collegeId:"
)

type (
	collegeInfoModel interface {
		Insert(ctx context.Context, data *CollegeInfo) (sql.Result, error)
		FindOne(ctx context.Context, collegeId int64) (*CollegeInfo, error)
		Update(ctx context.Context, data *CollegeInfo) error
		Delete(ctx context.Context, collegeId int64) error
	}

	defaultCollegeInfoModel struct {
		sqlc.CachedConn
		table string
	}

	CollegeInfo struct {
		CollegeId   int64          `db:"college_id"`   // 学院编号
		CollegeName sql.NullString `db:"college_name"` // 学院名称
	}
)

func newCollegeInfoModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCollegeInfoModel {
	return &defaultCollegeInfoModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."college_info"`,
	}
}

func (m *defaultCollegeInfoModel) Insert(ctx context.Context, data *CollegeInfo) (sql.Result, error) {
	publicCollegeInfoCollegeIdKey := fmt.Sprintf("%s%v", cachePublicCollegeInfoCollegeIdPrefix, data.CollegeId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, collegeInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CollegeId, data.CollegeName)
	}, publicCollegeInfoCollegeIdKey)
	return ret, err
}

func (m *defaultCollegeInfoModel) FindOne(ctx context.Context, collegeId int64) (*CollegeInfo, error) {
	publicCollegeInfoCollegeIdKey := fmt.Sprintf("%s%v", cachePublicCollegeInfoCollegeIdPrefix, collegeId)
	var resp CollegeInfo
	err := m.QueryRowCtx(ctx, &resp, publicCollegeInfoCollegeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where college_id = $1 limit 1", collegeInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, collegeId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollegeInfoModel) Update(ctx context.Context, data *CollegeInfo) error {
	publicCollegeInfoCollegeIdKey := fmt.Sprintf("%s%v", cachePublicCollegeInfoCollegeIdPrefix, data.CollegeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where college_id = $1", m.table, collegeInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CollegeId, data.CollegeName)
	}, publicCollegeInfoCollegeIdKey)
	return err
}

func (m *defaultCollegeInfoModel) Delete(ctx context.Context, collegeId int64) error {
	publicCollegeInfoCollegeIdKey := fmt.Sprintf("%s%v", cachePublicCollegeInfoCollegeIdPrefix, collegeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where college_id = $1", m.table)
		return conn.ExecCtx(ctx, query, collegeId)
	}, publicCollegeInfoCollegeIdKey)
	return err
}

func (m *defaultCollegeInfoModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicCollegeInfoCollegeIdPrefix, primary)
}

func (m *defaultCollegeInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where college_id = $1 limit 1", collegeInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCollegeInfoModel) tableName() string {
	return m.table
}
