// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: university.proto

package university

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStudentInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId string `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
}

func (x *GetStudentInfoReq) Reset() {
	*x = GetStudentInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_university_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentInfoReq) ProtoMessage() {}

func (x *GetStudentInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentInfoReq.ProtoReflect.Descriptor instead.
func (*GetStudentInfoReq) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{0}
}

func (x *GetStudentInfoReq) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetStudentInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId       string `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	StudentName     string `protobuf:"bytes,2,opt,name=studentName,proto3" json:"studentName,omitempty"`
	BindingUsername string `protobuf:"bytes,3,opt,name=bindingUsername,proto3" json:"bindingUsername,omitempty"`
}

func (x *GetStudentInfoResp) Reset() {
	*x = GetStudentInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_university_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentInfoResp) ProtoMessage() {}

func (x *GetStudentInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentInfoResp.ProtoReflect.Descriptor instead.
func (*GetStudentInfoResp) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentInfoResp) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentInfoResp) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *GetStudentInfoResp) GetBindingUsername() string {
	if x != nil {
		return x.BindingUsername
	}
	return ""
}

var File_university_proto protoreflect.FileDescriptor

var file_university_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x22, 0x31,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x7e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x32, 0x60, 0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x52,
	0x70, 0x63, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74,
	0x79, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_university_proto_rawDescOnce sync.Once
	file_university_proto_rawDescData = file_university_proto_rawDesc
)

func file_university_proto_rawDescGZIP() []byte {
	file_university_proto_rawDescOnce.Do(func() {
		file_university_proto_rawDescData = protoimpl.X.CompressGZIP(file_university_proto_rawDescData)
	})
	return file_university_proto_rawDescData
}

var file_university_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_university_proto_goTypes = []interface{}{
	(*GetStudentInfoReq)(nil),  // 0: university.GetStudentInfoReq
	(*GetStudentInfoResp)(nil), // 1: university.GetStudentInfoResp
}
var file_university_proto_depIdxs = []int32{
	0, // 0: university.UniversityRpc.GetStudentInfo:input_type -> university.GetStudentInfoReq
	1, // 1: university.UniversityRpc.GetStudentInfo:output_type -> university.GetStudentInfoResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_university_proto_init() }
func file_university_proto_init() {
	if File_university_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_university_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_university_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_university_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_university_proto_goTypes,
		DependencyIndexes: file_university_proto_depIdxs,
		MessageInfos:      file_university_proto_msgTypes,
	}.Build()
	File_university_proto = out.File
	file_university_proto_rawDesc = nil
	file_university_proto_goTypes = nil
	file_university_proto_depIdxs = nil
}
