// Code generated by goctl. DO NOT EDIT!
// Source: university.proto

package server

import (
	"context"

	"backend/app/university/rpc/internal/logic"
	"backend/app/university/rpc/internal/svc"
	"backend/app/university/rpc/university"
)

type UniversityRpcServer struct {
	svcCtx *svc.ServiceContext
	university.UnimplementedUniversityRpcServer
}

func NewUniversityRpcServer(svcCtx *svc.ServiceContext) *UniversityRpcServer {
	return &UniversityRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UniversityRpcServer) CollegeList(ctx context.Context, in *university.CollegeListReq) (*university.CollegeListResp, error) {
	l := logic.NewCollegeListLogic(ctx, s.svcCtx)
	return l.CollegeList(in)
}
