// Code generated by goctl. DO NOT EDIT!
// Source: university.proto

package server

import (
	"context"

	"backend/app/university_goctl/rpc/internal/logic"
	"backend/app/university_goctl/rpc/internal/svc"
	"backend/app/university_goctl/rpc/university"
)

type UniversityRpcServer struct {
	svcCtx *svc.ServiceContext
	university.UnimplementedUniversityRpcServer
}

func NewUniversityRpcServer(svcCtx *svc.ServiceContext) *UniversityRpcServer {
	return &UniversityRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UniversityRpcServer) GetStudentInfo(ctx context.Context, in *university.GetStudentInfoReq) (*university.GetStudentInfoResp, error) {
	l := logic.NewGetStudentInfoLogic(ctx, s.svcCtx)
	return l.GetStudentInfo(in)
}
